Remove "external :: system" declaration
This causes an error with the GNU Fortran compiler.  For example,

   LDT_smap_e_oplMod.F90:(.text+0xb6b): undefined reference to `system_'

This was added to suppress a warning issued by the Intel Fortran
compiler.