LIS will now terminate early after dumping files if GALWEM file is missing.
EXCEPTION:  LIS will terminate immediately if, on the initial time step,
less than 2 GALWEM GRIB files can be found (that's not enough to bookend
any part of the simulation).